# Generated by Django 6.0 on 2025-12-22 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Branch Name')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('is_main', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Carat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Carat Name')),
                ('purity', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Purity Factor')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Carat',
                'verbose_name_plural': 'Carats',
            },
        ),
        migrations.CreateModel(
            name='GoldPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_gram', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per Gram')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.carat')),
            ],
            options={
                'verbose_name': 'Gold Price',
                'verbose_name_plural': 'Gold Prices',
            },
        ),
    ]
