# Generated by Django 6.0 on 2025-12-24 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'فرع', 'verbose_name_plural': 'إعدادات - الفروع'},
        ),
        migrations.AlterModelOptions(
            name='carat',
            options={'verbose_name': 'عيار', 'verbose_name_plural': 'إعدادات - العيارات'},
        ),
        migrations.AlterModelOptions(
            name='goldprice',
            options={'verbose_name': 'سعر الذهب', 'verbose_name_plural': 'إعدادات - أسعار الذهب اليومية'},
        ),
    ]
