# Generated by Django 6.0 on 2025-12-24 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_branch_options_alter_carat_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='الفرع الرئيسي'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='الموقع'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الفرع'),
        ),
        migrations.AlterField(
            model_name='carat',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='carat',
            name='name',
            field=models.CharField(max_length=50, verbose_name='اسم العيار'),
        ),
        migrations.AlterField(
            model_name='carat',
            name='purity',
            field=models.DecimalField(decimal_places=4, max_digits=5, verbose_name='نسبة النقاء'),
        ),
        migrations.AlterField(
            model_name='goldprice',
            name='carat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.carat', verbose_name='العيار'),
        ),
        migrations.AlterField(
            model_name='goldprice',
            name='price_per_gram',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر للجرام'),
        ),
        migrations.AlterField(
            model_name='goldprice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
    ]
