# Generated by Django 6.0 on 2025-12-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_branch_is_main_alter_branch_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='Valunshy Gold ERP', max_length=100, verbose_name='اسم النظام')),
                ('base_url', models.URLField(blank=True, help_text='مثال: https://valunshy.pythonanywhere.com', verbose_name='رابط النظام (Base URL)')),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات - إعدادات النظام',
            },
        ),
    ]
