# Generated by Django 6.0 on 2025-12-25 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('view', 'عرض'), ('export', 'تصدير'), ('confirm', 'تأكيد'), ('reject', 'رفض')], max_length=20, verbose_name='الإجراء')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='الجدول')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='معرف السجل')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='المتصفح')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل نشاط',
                'verbose_name_plural': 'إدارة المستخدمين - سجل النشاطات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('general_manager', 'مدير عام'), ('sales_manager', 'مدير المبيعات'), ('inventory_manager', 'مدير المخزون'), ('manufacturing_manager', 'مدير التصنيع'), ('accountant', 'محاسب'), ('sales_rep', 'مندوب مبيعات'), ('cashier', 'كاشير'), ('customer', 'عميل')], default='sales_rep', max_length=30, verbose_name='الدور')),
                ('can_access_sales', models.BooleanField(default=False, verbose_name='صلاحية المبيعات')),
                ('can_access_inventory', models.BooleanField(default=False, verbose_name='صلاحية المخزون')),
                ('can_access_manufacturing', models.BooleanField(default=False, verbose_name='صلاحية التصنيع')),
                ('can_access_finance', models.BooleanField(default=False, verbose_name='صلاحية المالية')),
                ('can_access_crm', models.BooleanField(default=False, verbose_name='صلاحية العملاء')),
                ('can_access_reports', models.BooleanField(default=False, verbose_name='صلاحية التقارير')),
                ('can_access_settings', models.BooleanField(default=False, verbose_name='صلاحية الإعدادات')),
                ('can_confirm_invoices', models.BooleanField(default=False, verbose_name='صلاحية تأكيد الفواتير')),
                ('can_void_invoices', models.BooleanField(default=False, verbose_name='صلاحية إلغاء الفواتير')),
                ('can_edit_prices', models.BooleanField(default=False, verbose_name='صلاحية تعديل الأسعار')),
                ('can_view_costs', models.BooleanField(default=False, verbose_name='صلاحية عرض التكاليف')),
                ('can_export_data', models.BooleanField(default=False, verbose_name='صلاحية تصدير البيانات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch', verbose_name='الفرع')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف المستخدم',
                'verbose_name_plural': 'إدارة المستخدمين - الملفات الشخصية',
            },
        ),
    ]
