# Generated by Django 4.2.27 on 2026-01-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_activitylog_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='carat',
            name='base_weight',
            field=models.PositiveSmallIntegerField(default=21, help_text='مثال: 18، 21، 24', verbose_name='وزن العيار الأساسي'),
        ),
    ]
