# Generated by Django 6.0 on 2025-12-22 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_cash', to='finance.account')),
                ('cost_of_gold_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_cog', to='finance.account')),
                ('inventory_gold_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_inventory', to='finance.account')),
                ('sales_revenue_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_revenue', to='finance.account')),
                ('vat_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_vat', to='finance.account')),
            ],
            options={
                'verbose_name': 'Finance Settings',
                'verbose_name_plural': 'Finance Settings',
            },
        ),
    ]
