# Generated by Django 6.0 on 2025-12-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_financesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'حساب مالي', 'verbose_name_plural': 'الحسابات - شجرة الحسابات'},
        ),
        migrations.AlterModelOptions(
            name='financesettings',
            options={'verbose_name': 'إعدادات الحسابات', 'verbose_name_plural': 'إعدادات الحسابات'},
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'verbose_name': 'قيد يومية', 'verbose_name_plural': 'الحسابات - قيود اليومية'},
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('asset', 'أصول'), ('liability', 'خصوم'), ('equity', 'حقوق ملكية'), ('revenue', 'إيرادات'), ('expense', 'مصروفات')], max_length=20),
        ),
    ]
