# Generated by Django 6.0 on 2025-12-24 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_account_options_alter_financesettings_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم السنة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('is_active', models.BooleanField(default=False, verbose_name='السنة الحالية')),
                ('is_closed', models.BooleanField(default=False, verbose_name='مغلقة')),
            ],
            options={
                'verbose_name': 'سنة مالية',
                'verbose_name_plural': 'الحسابات - السنوات المالية',
            },
        ),
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='رصيد مدين')),
                ('credit_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='رصيد دائن')),
                ('gold_balance', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='رصيد الذهب (جرام)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.account', verbose_name='الحساب')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.fiscalyear', verbose_name='السنة المالية')),
            ],
            options={
                'verbose_name': 'رصيد افتتاحي',
                'verbose_name_plural': 'الحسابات - الأرصدة الافتتاحية',
                'unique_together': {('fiscal_year', 'account')},
            },
        ),
    ]
