# Generated by Django 6.0 on 2025-12-24 09:48

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_fiscalyear_openingbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='اسم السنة'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateField(default=django.db.models.functions.datetime.Now, verbose_name='تاريخ القيد'),
        ),
    ]
