# Generated by Django 6.0 on 2025-12-24 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_fiscalyear_name_alter_journalentry_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledgerentry',
            options={'verbose_name': 'بند القيد', 'verbose_name_plural': 'بنود القيود'},
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='description',
            field=models.TextField(verbose_name='الوصف / البيان'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='reference',
            field=models.CharField(max_length=100, verbose_name='رقم المرجع'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.account', verbose_name='الحساب'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='دائن (نقد)'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مدين (نقد)'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='gold_credit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='دائن (ذهب)'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='gold_debit',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='مدين (ذهب)'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='finance.journalentry', verbose_name='قيد اليومية'),
        ),
    ]
