# Generated by Django 6.0 on 2025-12-24 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_ledgerentry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('asset', 'أصول'), ('liability', 'خصوم'), ('equity', 'حقوق ملكية'), ('revenue', 'إيرادات'), ('expense', 'مصروفات')], max_length=20, verbose_name='نوع الحساب'),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد النقدي'),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='كود الحساب'),
        ),
        migrations.AlterField(
            model_name='account',
            name='gold_balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='رصيد الذهب (جرام)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الحساب'),
        ),
        migrations.AlterField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='finance.account', verbose_name='الحساب الأب'),
        ),
        migrations.AlterField(
            model_name='financesettings',
            name='cash_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_cash', to='finance.account', verbose_name='حساب النقدية'),
        ),
        migrations.AlterField(
            model_name='financesettings',
            name='cost_of_gold_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_cog', to='finance.account', verbose_name='حساب تكلفة الذهب'),
        ),
        migrations.AlterField(
            model_name='financesettings',
            name='inventory_gold_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_inventory', to='finance.account', verbose_name='حساب مخزون الذهب'),
        ),
        migrations.AlterField(
            model_name='financesettings',
            name='sales_revenue_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_revenue', to='finance.account', verbose_name='حساب إيرادات المبيعات'),
        ),
        migrations.AlterField(
            model_name='financesettings',
            name='vat_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_vat', to='finance.account', verbose_name='حساب ضريبة القيمة المضافة'),
        ),
    ]
