# Generated by Django 6.0 on 2025-12-24 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_custodyholder_custody_custodysettlement_treasury_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasury',
            name='linked_account',
            field=models.ForeignKey(blank=True, help_text='الحساب الذي سيتم التأثير عليه في قيود اليومية', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.account', verbose_name='الحساب المالي المرتبط'),
        ),
    ]
