# Generated by Django 6.0 on 2025-12-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_treasury_linked_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasury',
            name='gold_casting_balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='رصيد ذهب للسبك'),
        ),
        migrations.AddField(
            model_name='treasury',
            name='stones_balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='رصيد أحجار للتصنيع'),
        ),
    ]
