# Generated by Django 6.0 on 2025-12-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_treasury_gold_casting_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytreasuryreport',
            name='actual_gold_casting',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='سبك فعلي'),
        ),
        migrations.AddField(
            model_name='dailytreasuryreport',
            name='actual_stones',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='أحجار فعلي'),
        ),
        migrations.AddField(
            model_name='dailytreasuryreport',
            name='closing_gold_casting',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='رصيد سبك ختامي'),
        ),
        migrations.AddField(
            model_name='dailytreasuryreport',
            name='closing_stones',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='رصيد أحجار ختامي'),
        ),
        migrations.AddField(
            model_name='dailytreasuryreport',
            name='gold_casting_difference',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='فرق سبك'),
        ),
        migrations.AddField(
            model_name='dailytreasuryreport',
            name='opening_gold_casting',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='رصيد سبك افتتاحي'),
        ),
        migrations.AddField(
            model_name='dailytreasuryreport',
            name='opening_stones',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='رصيد أحجار افتتاحي'),
        ),
        migrations.AddField(
            model_name='dailytreasuryreport',
            name='stones_difference',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='فرق أحجار'),
        ),
    ]
