# Generated by Django 6.0 on 2025-12-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_dailytreasuryreport_actual_gold_casting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasurytransaction',
            name='balance_after_gold_casting',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='رصيد السبك بعد الحركة'),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='balance_after_stones',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='رصيد الأحجار بعد الحركة'),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='gold_casting_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='وزن ذهب سبك'),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='stones_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='وزن أحجار'),
        ),
    ]
