# Generated by Django 6.0 on 2025-12-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_alter_treasury_treasury_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasury',
            name='treasury_type',
            field=models.CharField(choices=[('main', 'الخزينة الرئيسية'), ('branch', 'خزينة فرع'), ('petty', 'خزينة مصروفات نثرية'), ('gold_raw', 'خزينة ذهب خام (للسبك)'), ('stones', 'خزينة أحجار للتصنيع'), ('finished', 'خزينة إنتاج تام'), ('gold_tools', 'خزينة أدوات تصنيع (ذهب)'), ('production', 'خزينة قسم الإنتاج'), ('casting', 'خزينة قسم السبك')], default='main', max_length=20, verbose_name='نوع الخزينة'),
        ),
    ]
