# Generated by Django 6.0 on 2025-12-26 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_alter_treasury_treasury_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود المركز')),
                ('name', models.CharField(max_length=100, verbose_name='اسم مركز التكلفة')),
                ('description', models.TextField(blank=True, verbose_name='وصف المركز')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مركز تكلفة',
                'verbose_name_plural': 'الحسابات - مراكز التكلفة',
            },
        ),
        migrations.AddField(
            model_name='expensevoucher',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.costcenter', verbose_name='مركز التكلفة'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.costcenter', verbose_name='مركز التكلفة'),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.costcenter', verbose_name='مركز التكلفة'),
        ),
    ]
