# Generated by Django 6.0 on 2025-12-26 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_costcenter_expensevoucher_cost_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasurytransaction',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.costcenter', verbose_name='مركز التكلفة'),
        ),
    ]
