# Generated by Django 6.0 on 2025-12-26 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_treasurytransaction_cost_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasurytransfer',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.costcenter', verbose_name='مركز التكلفة'),
        ),
    ]
