# Generated by Django 6.0 on 2025-12-26 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_treasurytransfer_cost_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesettings',
            name='sales_treasury',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_sales', to='finance.treasury', verbose_name='خزينة المبيعات الافتراضية'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='treasury_type',
            field=models.CharField(choices=[('main', 'الخزينة الرئيسية'), ('branch', 'خزينة فرع'), ('petty', 'خزينة مصروفات نثرية'), ('sales', 'خزينة مبيعات'), ('gold_raw', 'خزينة ذهب خام (للسبك)'), ('stones', 'خزينة أحجار للتصنيع'), ('finished', 'خزينة إنتاج تام'), ('gold_tools', 'خزينة أدوات تصنيع (ذهب)'), ('production', 'خزينة قسم الإنتاج'), ('casting', 'خزينة قسم السبك')], default='main', max_length=20, verbose_name='نوع الخزينة'),
        ),
        migrations.AlterField(
            model_name='treasurytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('cash_in', 'إيداع نقدي'), ('cash_out', 'صرف نقدي'), ('gold_in', 'إيداع ذهب'), ('gold_out', 'صرف ذهب'), ('transfer_in', 'تحويل وارد'), ('transfer_out', 'تحويل صادر'), ('finished_goods_in', 'وارد إنتاج تام'), ('adjustment', 'تسوية')], max_length=20, verbose_name='نوع الحركة'),
        ),
    ]
