# Generated by Django 6.0 on 2025-12-27 13:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_financesettings_sales_treasury_and_more'),
        ('manufacturing', '0029_alter_productionstage_options_workshoptransfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustodyTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الكمية المصروفة')),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='الوزن المصروف (جرام)')),
                ('returned_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الكمية المردودة')),
                ('returned_weight', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='الوزن المردود (جرام)')),
                ('custody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='finance.custody', verbose_name='سند العهدة')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.installationtool', verbose_name='الأداة/المستلزم')),
            ],
            options={
                'verbose_name': 'مستلزم عهدة',
                'verbose_name_plural': 'مستلزمات العهد',
            },
        ),
        migrations.CreateModel(
            name='ToolTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(max_length=50, unique=True, verbose_name='رقم التحويل')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الكمية المحولة')),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='الوزن المحول (جرام)')),
                ('status', models.CharField(choices=[('pending', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_tool_transfers', to=settings.AUTH_USER_MODEL, verbose_name='أكد الاستلام')),
                ('from_treasury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_transfers_out', to='finance.treasury', verbose_name='من خزينة')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_tool_transfers', to=settings.AUTH_USER_MODEL, verbose_name='بادر بالتحويل')),
                ('to_treasury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_transfers_in', to='finance.treasury', verbose_name='إلى خزينة')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.installationtool', verbose_name='الأداة/المستلزم')),
            ],
            options={
                'verbose_name': 'تحويل مستلزمات',
                'verbose_name_plural': 'تحويلات المستلزمات',
            },
        ),
        migrations.CreateModel(
            name='TreasuryTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الكمية المتوفرة')),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='الوزن المتوفر (جرام)')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.installationtool', verbose_name='الأداة/المستلزم')),
                ('treasury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_balances', to='finance.treasury', verbose_name='الخزينة')),
            ],
            options={
                'verbose_name': 'رصيد مستلزمات الخزينة',
                'verbose_name_plural': 'أرصدة مستلزمات الخزائن',
                'unique_together': {('treasury', 'tool')},
            },
        ),
    ]
