# Generated by Django 6.0 on 2025-12-27 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_custodytool_tooltransfer_treasurytool'),
        ('manufacturing', '0029_alter_productionstage_options_workshoptransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasury',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasuries', to='manufacturing.workshop', verbose_name='الورشة المرتبطة'),
        ),
    ]
