# Generated by Django 6.0 on 2025-12-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_treasury_workshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasurytransfer',
            name='stones_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='وزن الأحجار'),
        ),
    ]
