# Generated by Django 6.0 on 2025-12-29 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_treasurytransfer_stones_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasury',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_treasuries', to='finance.treasury', verbose_name='الخزينة الأم'),
        ),
    ]
