# Generated by Django 6.0 on 2025-12-29 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_treasury_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الشريك')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='النسبة المئوية من 100', max_digits=5, verbose_name='نسبة الشراكة %')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('joined_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.account', verbose_name='حساب جاري الشريك')),
            ],
            options={
                'verbose_name': 'شريك',
                'verbose_name_plural': 'الشركاء',
            },
        ),
    ]
