# Generated by Django 4.2.27 on 2026-01-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensevoucher',
            name='expense_category',
            field=models.CharField(choices=[('electricity', 'كهرباء'), ('water', 'مياه'), ('gas', 'غاز'), ('rent', 'إيجار'), ('salaries', 'رواتب'), ('maintenance', 'صيانة'), ('supplies', 'مستلزمات'), ('transport', 'نقل ومواصلات'), ('marketing', 'تسويق'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='تصنيف المصروف'),
        ),
        migrations.AlterField(
            model_name='treasury',
            name='treasury_type',
            field=models.CharField(choices=[('main', 'الخزينة الرئيسية'), ('branch', 'خزينة فرع'), ('petty', 'خزينة مصروفات نثرية'), ('sales', 'خزينة مبيعات'), ('gold_raw', 'خزينة ذهب خام (للسبك)'), ('stones', 'خزينة أحجار للتصنيع'), ('finished', 'خزينة إنتاج تام'), ('gold_tools', 'خزينة أدوات تصنيع (ذهب)'), ('production', 'خزينة قسم الإنتاج'), ('casting', 'خزينة قسم السبك'), ('laser_powder', 'خزينة بودر ليزر'), ('laser_scrap', 'خزينة خسية الليزر'), ('casting_powder', 'خزينة بودر سبك'), ('casting_scrap', 'خزينة خسية سبك'), ('laser', 'خزينة ليزر')], default='main', max_length=20, verbose_name='نوع الخزينة'),
        ),
    ]
