# Generated by Django 4.2.27 on 2026-01-02 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_alter_treasury_treasury_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم النوع')),
                ('code', models.SlugField(unique=True, verbose_name='كود النوع')),
                ('color', models.CharField(default='#666666', help_text='كود اللون Hex (مثال: #4CAF50)', max_length=20, verbose_name='لون التمييز')),
                ('description', models.TextField(blank=True, verbose_name='وصف')),
            ],
            options={
                'verbose_name': 'نوع خزينة',
                'verbose_name_plural': 'أنواع الخزائن',
            },
        ),
        migrations.AlterField(
            model_name='treasury',
            name='treasury_type',
            field=models.CharField(choices=[('main', 'الخزينة الرئيسية'), ('branch', 'خزينة فرع'), ('petty', 'خزينة مصروفات نثرية'), ('sales', 'خزينة مبيعات'), ('workshop', 'خزينة ورشة'), ('gold_raw', 'خزينة ذهب خام (للسبك)'), ('stones', 'خزينة أحجار للتصنيع'), ('finished', 'خزينة إنتاج تام'), ('gold_tools', 'خزينة أدوات تصنيع (ذهب)'), ('production', 'خزينة قسم الإنتاج'), ('casting', 'خزينة قسم السبك'), ('laser_powder', 'خزينة بودر ليزر'), ('laser_scrap', 'خزينة خسية الليزر'), ('casting_powder', 'خزينة بودر سبك'), ('casting_scrap', 'خزينة خسية سبك'), ('laser', 'خزينة ليزر')], default='main', max_length=20, verbose_name='نوع الخزينة (قديم)'),
        ),
        migrations.AddField(
            model_name='treasury',
            name='treasury_type_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.treasurytype', verbose_name='نوع الخزينة'),
        ),
    ]
