# Generated by Django 4.2.27 on 2026-01-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_treasurytype_alter_treasury_treasury_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treasury',
            name='treasury_type',
        ),
        migrations.RenameField(
            model_name='treasury',
            old_name='treasury_type_new',
            new_name='treasury_type',
        ),
    ]
