# Generated by Django 4.2.27 on 2026-01-04 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0028_remove_treasury_treasury_type_new_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'حساب مالي', 'verbose_name_plural': 'شجرة الحسابات'},
        ),
        migrations.AlterModelOptions(
            name='costcenter',
            options={'verbose_name': 'مركز تكلفة', 'verbose_name_plural': 'مراكز التكلفة'},
        ),
        migrations.AlterModelOptions(
            name='custody',
            options={'ordering': ['-issue_date', '-created_at'], 'verbose_name': 'سند عهدة', 'verbose_name_plural': 'سندات العهد'},
        ),
        migrations.AlterModelOptions(
            name='custodyholder',
            options={'verbose_name': 'مستلم عهدة', 'verbose_name_plural': 'مستلمي العهد'},
        ),
        migrations.AlterModelOptions(
            name='dailytreasuryreport',
            options={'ordering': ['-date'], 'verbose_name': 'تقرير خزينة يومي', 'verbose_name_plural': 'التقارير اليومية'},
        ),
        migrations.AlterModelOptions(
            name='expensevoucher',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'إذن صرف', 'verbose_name_plural': 'أذون الصرف'},
        ),
        migrations.AlterModelOptions(
            name='fiscalyear',
            options={'verbose_name': 'سنة مالية', 'verbose_name_plural': 'السنوات المالية'},
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'verbose_name': 'قيد يومية', 'verbose_name_plural': 'قيود اليومية'},
        ),
        migrations.AlterModelOptions(
            name='openingbalance',
            options={'verbose_name': 'رصيد افتتاحي', 'verbose_name_plural': 'الأرصدة الافتتاحية'},
        ),
        migrations.AlterModelOptions(
            name='receiptvoucher',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'إذن قبض', 'verbose_name_plural': 'أذون القبض'},
        ),
        migrations.AlterModelOptions(
            name='treasury',
            options={'verbose_name': 'خزينة', 'verbose_name_plural': 'الخزائن'},
        ),
        migrations.AlterModelOptions(
            name='treasurytransaction',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'حركة خزينة', 'verbose_name_plural': 'حركات الخزينة'},
        ),
        migrations.AlterModelOptions(
            name='treasurytransfer',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'تحويل بين خزائن', 'verbose_name_plural': 'التحويلات'},
        ),
    ]
