# Generated by Django 4.2.27 on 2026-01-04 23:32

from django.db import migrations, models
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0029_alter_account_options_alter_costcenter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateField(db_index=True, default=django.db.models.functions.datetime.Now, verbose_name='تاريخ القيد'),
        ),
    ]
