# Generated by Django 4.2.27 on 2026-01-04 23:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0030_alter_journalentry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasurytransaction',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='التاريخ'),
        ),
    ]
