# Generated by Django 6.0 on 2025-12-22 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Barcode')),
                ('name', models.CharField(max_length=255, verbose_name='Item Name')),
                ('gross_weight', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Gross Weight')),
                ('stone_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Stone Weight')),
                ('net_gold_weight', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Net Gold Weight')),
                ('labor_fee_per_gram', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Labor Fee/Gram')),
                ('fixed_labor_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Fixed Labor Fee')),
                ('rfid_tag', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='RFID Tag')),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('manufacturing', 'In Manufacturing'), ('mandoob', 'With Delegate'), ('lost', 'Lost')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.carat')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.category')),
                ('current_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.branch')),
            ],
            options={
                'verbose_name': 'Jewelry Item',
                'verbose_name_plural': 'Jewelry Items',
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Material Name')),
                ('material_type', models.CharField(choices=[('gold_bar', 'Gold Bar'), ('gold_grain', 'Gold Grain'), ('stones', 'Stones'), ('scrap', 'Scrap Gold')], max_length=20)),
                ('current_weight', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Current Weight')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branch')),
                ('carat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.carat')),
            ],
        ),
    ]
