# Generated by Django 6.0 on 2025-12-24 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_branch_options_alter_carat_options_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'تصنيف', 'verbose_name_plural': 'التصنيفات'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'قطعة ذهب', 'verbose_name_plural': 'المخزون - القطع'},
        ),
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='الباركود'),
        ),
        migrations.AlterField(
            model_name='item',
            name='carat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.carat', verbose_name='العيار'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.category', verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='item',
            name='current_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.branch', verbose_name='الفرع الحالي'),
        ),
        migrations.AlterField(
            model_name='item',
            name='fixed_labor_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مصنعية ثابتة'),
        ),
        migrations.AlterField(
            model_name='item',
            name='gross_weight',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='الوزن القائم'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='صورة القطعة'),
        ),
        migrations.AlterField(
            model_name='item',
            name='labor_fee_per_gram',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المصنعية/جرام'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم الصنف'),
        ),
        migrations.AlterField(
            model_name='item',
            name='net_gold_weight',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='صافي الذهب'),
        ),
        migrations.AlterField(
            model_name='item',
            name='rfid_tag',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='كود RFID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('manufacturing', 'In Manufacturing'), ('mandoob', 'With Delegate'), ('lost', 'Lost')], default='available', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='item',
            name='stone_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='وزن الأحجار'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='material_type',
            field=models.CharField(choices=[('gold_bar', 'سبائك ذهب'), ('gold_grain', 'حبيبات ذهب'), ('stones', 'أحجار كريمة'), ('scrap', 'ذهب كسر')], max_length=20),
        ),
    ]
