# Generated by Django 6.0 on 2025-12-24 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_branch_is_main_alter_branch_location_and_more'),
        ('inventory', '0002_alter_category_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawmaterial',
            options={'verbose_name': 'مادة خام', 'verbose_name_plural': 'المخزون - المواد الخام'},
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branch', verbose_name='الفرع'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='carat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.carat', verbose_name='العيار'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='current_weight',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الوزن الحالي'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='material_type',
            field=models.CharField(choices=[('gold_bar', 'سبائك ذهب'), ('gold_grain', 'حبيبات ذهب'), ('stones', 'أحجار كريمة'), ('scrap', 'ذهب كسر')], max_length=20, verbose_name='نوع المادة'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم المادة'),
        ),
    ]
