# Generated by Django 6.0 on 2025-12-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_rawmaterial_options_alter_rawmaterial_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='retail_margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='هامش ربح التجزئة'),
        ),
    ]
