# Generated by Django 6.0 on 2025-12-27 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_activitylog_userprofile'),
        ('inventory', '0004_item_retail_margin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(max_length=50, unique=True, verbose_name='رقم التحويل')),
                ('status', models.CharField(choices=[('pending', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('date', models.DateField(auto_now_add=True, verbose_name='التاريخ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_item_transfers', to=settings.AUTH_USER_MODEL, verbose_name='أكد الاستلام')),
                ('from_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_transfers_out', to='core.branch', verbose_name='من فرع')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_item_transfers', to=settings.AUTH_USER_MODEL, verbose_name='بادر بالتحويل')),
                ('items', models.ManyToManyField(related_name='transfers', to='inventory.item', verbose_name='القطع')),
                ('to_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_transfers_in', to='core.branch', verbose_name='إلى فرع/قسم')),
            ],
            options={
                'verbose_name': 'تحويل قطع',
                'verbose_name_plural': 'المخزون - تحويلات القطع',
            },
        ),
        migrations.CreateModel(
            name='MaterialTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(max_length=50, unique=True, verbose_name='رقم التحويل')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الوزن المحول')),
                ('status', models.CharField(choices=[('pending', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('date', models.DateField(auto_now_add=True, verbose_name='التاريخ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_material_transfers', to=settings.AUTH_USER_MODEL, verbose_name='أكد الاستلام')),
                ('from_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_transfers_out', to='core.branch', verbose_name='من فرع')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_material_transfers', to=settings.AUTH_USER_MODEL, verbose_name='بادر بالتحويل')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.rawmaterial', verbose_name='المادة الخام')),
                ('to_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_transfers_in', to='core.branch', verbose_name='إلى فرع/قسم')),
            ],
            options={
                'verbose_name': 'تحويل مواد خام',
                'verbose_name_plural': 'المخزون - تحويلات المواد الخام',
            },
        ),
    ]
