# Generated by Django 4.2.27 on 2026-01-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='overhead_electricity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='نصيب الكهرباء'),
        ),
        migrations.AddField(
            model_name='item',
            name='overhead_gas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='نصيب الغاز'),
        ),
        migrations.AddField(
            model_name='item',
            name='overhead_other',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='نصيب مصاريف أخرى'),
        ),
        migrations.AddField(
            model_name='item',
            name='overhead_rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='نصيب الإيجار'),
        ),
        migrations.AddField(
            model_name='item',
            name='overhead_salaries',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='نصيب الرواتب'),
        ),
        migrations.AddField(
            model_name='item',
            name='overhead_water',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='نصيب المياه'),
        ),
        migrations.AlterField(
            model_name='item',
            name='fixed_labor_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مصنعية ثابتة (أجور + ربح مصنع)'),
        ),
    ]
