# Generated by Django 4.2.27 on 2026-01-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_item_overhead_electricity_item_overhead_gas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='default_stone_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قيمة الأحجار الافتراضية'),
        ),
    ]
