# Generated by Django 4.2.27 on 2026-01-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_item_default_stone_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('manufacturing', 'In Manufacturing'), ('mandoob', 'With Delegate'), ('reserved', 'Mahjouz (Reserved)'), ('lost', 'Lost')], db_index=True, default='available', max_length=20, verbose_name='الحالة'),
        ),
    ]
