# Generated by Django 4.2.27 on 2026-01-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='barcode_prefix',
            field=models.CharField(blank=True, help_text='مثال: VT للخاتم توينز, VW للدبلة', max_length=10, verbose_name='بادئة الباركود'),
        ),
    ]
