# Generated by Django 4.2.27 on 2026-01-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_category_barcode_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=100, unique=True, verbose_name='الباركود'),
        ),
    ]
