# Generated by Django 6.0 on 2025-12-22 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Order Number')),
                ('input_weight', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Input Gold Weight')),
                ('output_weight', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Output Items weight')),
                ('scrap_weight', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Scrap/Loss Weight')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('casting', 'Casting (سبك)'), ('crafting', 'Crafting (صياغة)'), ('polishing', 'Polishing (تلميع)'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('assigned_technician', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('carat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.carat')),
            ],
            options={
                'verbose_name': 'Manufacturing Order',
                'verbose_name_plural': 'Manufacturing Orders',
            },
        ),
        migrations.CreateModel(
            name='ProductionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=100)),
                ('input_weight', models.DecimalField(decimal_places=3, max_digits=12)),
                ('output_weight', models.DecimalField(decimal_places=3, max_digits=12)),
                ('technician', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='manufacturing.manufacturingorder')),
            ],
        ),
    ]
