# Generated by Django 6.0 on 2025-12-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionstage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='production_stages/', verbose_name='Stage Photo'),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
    ]
