# Generated by Django 6.0 on 2025-12-24 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_branch_options_alter_carat_options_and_more'),
        ('manufacturing', '0002_productionstage_image_productionstage_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturingorder',
            options={'verbose_name': 'أمر تصنيع', 'verbose_name_plural': 'التصنيع - أوامر العمل'},
        ),
        migrations.AlterModelOptions(
            name='productionstage',
            options={'verbose_name': 'مرحلة إنتاج', 'verbose_name_plural': 'مراحل التصنيع'},
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='assigned_technician',
            field=models.CharField(blank=True, max_length=255, verbose_name='الفني المسؤول'),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='carat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.carat', verbose_name='العيار'),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='input_weight',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='وزن الذهب الداخل'),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='order_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم الأمر'),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='output_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='وزن القطع الناتجة'),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='scrap_weight',
            field=models.DecimalField(decimal_places=3, default=0, help_text='المعيار المصري: السبك (0.5-1%)، الشغل (1.5-2.5%)، الإجمالي المقبول (2-3%)', max_digits=12, verbose_name='وزن الهالك/الخسية'),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='تاريخ البدء'),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('casting', 'سبك'), ('crafting', 'صياغة'), ('polishing', 'تلميع / واجهة'), ('completed', 'مكتمل / جاهز'), ('cancelled', 'ملغى')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='productionstage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='production_stages/', verbose_name='صورة المرحلة'),
        ),
        migrations.AlterField(
            model_name='productionstage',
            name='input_weight',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الوزن الداخل'),
        ),
        migrations.AlterField(
            model_name='productionstage',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='productionstage',
            name='output_weight',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الوزن الخارج'),
        ),
        migrations.AlterField(
            model_name='productionstage',
            name='stage_name',
            field=models.CharField(max_length=100, verbose_name='اسم المرحلة'),
        ),
        migrations.AlterField(
            model_name='productionstage',
            name='technician',
            field=models.CharField(max_length=255, verbose_name='الفني المسؤول'),
        ),
    ]
