# Generated by Django 6.0 on 2025-12-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0003_alter_manufacturingorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionstage',
            name='stage_name',
            field=models.CharField(choices=[('design', 'تصميم / 3D Design'), ('printing', 'طباعة الشمع / 3D Printing'), ('casting', 'السبك / Casting'), ('filing', 'البرد والتجهيز / Filing'), ('mounting', 'التركيب / Mounting'), ('setting', 'تركيب الأحجار / Stone Setting'), ('polishing', 'الجلي والتلميع / Polishing'), ('plating', 'الطلاء / Plating'), ('qc', 'مراقبة الجودة / Quality Control')], default='casting', max_length=20, verbose_name='اسم المرحلة'),
        ),
    ]
