# Generated by Django 6.0 on 2025-12-24 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_rawmaterial_options_alter_rawmaterial_branch_and_more'),
        ('manufacturing', '0004_alter_productionstage_stage_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الورشة')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='المسؤول')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('gold_balance_18', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='رصيد ذهب 18 (جرام)')),
                ('gold_balance_21', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='رصيد ذهب 21 (جرام)')),
                ('gold_balance_24', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='رصيد ذهب 24 (جرام)')),
                ('labor_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='رصيد المصنعيات (نقد)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ورشة فنية',
                'verbose_name_plural': 'التصنيع - الورش',
            },
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='input_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.rawmaterial', verbose_name='المادة الخام المصروفة'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='workshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='manufacturing.workshop', verbose_name='الورشة'),
        ),
    ]
