# Generated by Django 6.0 on 2025-12-24 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0005_workshop_manufacturingorder_input_material_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الحفر/الحجر')),
                ('stone_type', models.CharField(blank=True, max_length=50, verbose_name='النوع')),
                ('unit', models.CharField(default='قيراط', max_length=20, verbose_name='الوحدة')),
                ('current_stock', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='الرصيد الحالي')),
            ],
            options={
                'verbose_name': 'حجر كريم / فص',
                'verbose_name_plural': 'التصنيع - مخزن الفصوص',
            },
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='labor_cost_per_gram',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تكلفة المصنعية للجرام'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='total_labor_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي أجر الورشة'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='total_stone_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='إجمالي وزن الفصوص (جم)'),
        ),
        migrations.CreateModel(
            name='OrderStone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='الكمية/الوزن المصروف')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.manufacturingorder')),
                ('stone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.stone', verbose_name='الحجر')),
            ],
            options={
                'verbose_name': 'فص في أمر',
                'verbose_name_plural': 'فصوص الأوامر',
            },
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='stones',
            field=models.ManyToManyField(through='manufacturing.OrderStone', to='manufacturing.stone', verbose_name='الفصوص المستخدمة'),
        ),
    ]
