# Generated by Django 6.0 on 2025-12-24 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_branch_is_main_alter_branch_location_and_more'),
        ('manufacturing', '0006_stone_manufacturingorder_labor_cost_per_gram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingorder',
            name='auto_create_item',
            field=models.BooleanField(default=True, verbose_name='إنشاء قطعة في المخزن تلقائياً عند الاكتمال'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='item_name_pattern',
            field=models.CharField(blank=True, help_text='مثال: خاتم ذهب عيار 21', max_length=255, verbose_name='اسم الصنف الناتج'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='target_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch', verbose_name='الفرع المستلم'),
        ),
        migrations.CreateModel(
            name='WorkshopSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاريخ التسوية')),
                ('settlement_type', models.CharField(choices=[('gold_payment', 'دفع ذهب للورشة'), ('labor_payment', 'دفع مصنعيات (نقد)'), ('scrap_receive', 'استلام خسية/هالك')], max_length=20, verbose_name='نوع التسوية')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='المبلغ النقدي')),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='الوزن (جرام)')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='رقم السند/المرجع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات إضافية')),
                ('carat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.carat', verbose_name='العيار (في حالة الذهب)')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='manufacturing.workshop', verbose_name='الورشة')),
            ],
            options={
                'verbose_name': 'تسويه ورشة',
                'verbose_name_plural': 'التصنيع - تسويات الورش',
            },
        ),
    ]
