# Generated by Django 6.0 on 2025-12-24 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_rawmaterial_options_alter_rawmaterial_branch_and_more'),
        ('manufacturing', '0007_manufacturingorder_auto_create_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingorder',
            name='resulting_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_order', to='inventory.item', verbose_name='القطعة الناتجة في المخزن'),
        ),
    ]
