# Generated by Django 6.0 on 2025-12-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0008_manufacturingorder_resulting_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopsettlement',
            name='gross_weight',
            field=models.DecimalField(decimal_places=3, default=0, help_text='وزن البودر كما هو', max_digits=12, verbose_name='الوزن القائم (قبل التحليل)'),
        ),
        migrations.AlterField(
            model_name='workshopsettlement',
            name='settlement_type',
            field=models.CharField(choices=[('gold_payment', 'دفع ذهب للورشة'), ('labor_payment', 'دفع مصنعيات (نقد)'), ('scrap_receive', 'استلام خسية/هالك (واضح)'), ('powder_receive', 'استلام بودر/جلي (يحتاج تحليل)')], max_length=20, verbose_name='نوع التسوية'),
        ),
        migrations.AlterField(
            model_name='workshopsettlement',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='الوزن الصافي (بعد التحليل)'),
        ),
    ]
