# Generated by Django 6.0 on 2025-12-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0009_workshopsettlement_gross_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='filings_balance_18',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='رصيد براده 18 (جرام)'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='filings_balance_21',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='رصيد براده 21 (جرام)'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='filings_balance_24',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='رصيد براده 24 (جرام)'),
        ),
    ]
