# Generated by Django 6.0 on 2025-12-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0010_workshop_filings_balance_18_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturingorder',
            name='labor_cost_per_gram',
        ),
        migrations.RemoveField(
            model_name='manufacturingorder',
            name='total_labor_cost',
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='labor_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='اتركه 0 إذا كنت ستدخل الأجر الإجمالي يدوياً', max_digits=10, verbose_name='أجر الجرام (اختياري)'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='manufacturing_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='أجر التصنيع (ثابت / مرتب)'),
        ),
    ]
