# Generated by Django 6.0 on 2025-12-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0011_remove_manufacturingorder_labor_cost_per_gram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingorder',
            name='labor_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='اتركه 0 للورش الداخلية (نظام المرتبات)', max_digits=10, verbose_name='أجر الجرام (للورش الخارجية)'),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='manufacturing_pay',
            field=models.DecimalField(decimal_places=2, default=0, help_text='المبلغ الذي سيتم إضافته لرصيد الورشة. اتركه 0 للورش الداخلية.', max_digits=12, verbose_name='إجمالي الأجر المستحق'),
        ),
    ]
