# Generated by Django 6.0 on 2025-12-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0012_alter_manufacturingorder_labor_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='filings_balance_21',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='filings_balance_24',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='gold_balance_21',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='gold_balance_24',
        ),
        migrations.AlterField(
            model_name='workshop',
            name='filings_balance_18',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='رصيد البراده (جرام)'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='gold_balance_18',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='رصيد الذهب (جرام)'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='labor_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='رصيد النقدية (مصنعيات)'),
        ),
    ]
