# Generated by Django 6.0 on 2025-12-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0013_remove_workshop_filings_balance_21_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الأداة/المستلزم')),
                ('description', models.TextField(blank=True, verbose_name='الوصف/المواصفات')),
                ('quantity', models.IntegerField(default=0, verbose_name='العدد المتوفر')),
                ('min_quantity', models.IntegerField(default=1, verbose_name='حد الطلب')),
                ('tool_type', models.CharField(choices=[('consumable', 'مستهلكات (شمع/جبس/..)'), ('equipment', 'عدد وأدوات (مبارد/زراديات/..)'), ('spare_part', 'قطع غيار ماكينات')], default='consumable', max_length=20, verbose_name='نوع الأداة')),
            ],
            options={
                'verbose_name': 'أداة تركيب / مستلزمات',
                'verbose_name_plural': 'التصنيع - مخزن أدوات التركيب',
            },
        ),
    ]
