# Generated by Django 6.0 on 2025-12-26 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_activitylog_userprofile'),
        ('manufacturing', '0014_installationtool'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationtool',
            name='carat',
            field=models.ForeignKey(blank=True, help_text='للأدوات الذهبية فقط', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.carat', verbose_name='العيار'),
        ),
        migrations.AddField(
            model_name='installationtool',
            name='min_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='حد الوزن الأدنى'),
        ),
        migrations.AddField(
            model_name='installationtool',
            name='unit',
            field=models.CharField(choices=[('piece', 'قطعة'), ('gram', 'جرام'), ('meter', 'متر'), ('roll', 'لفة')], default='piece', max_length=10, verbose_name='وحدة القياس'),
        ),
        migrations.AddField(
            model_name='installationtool',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='الوزن (جرام)'),
        ),
        migrations.AlterField(
            model_name='installationtool',
            name='tool_type',
            field=models.CharField(choices=[('consumable', 'مستهلكات (شمع/جبس/..)'), ('equipment', 'عدد وأدوات (مبارد/زراديات/..)'), ('spare_part', 'قطع غيار ماكينات'), ('gold_wire', 'سلك ذهب (ليزر/لحام)'), ('gold_solder', 'لحام ذهب'), ('cadmium', 'كيديم'), ('gold_sheet', 'رقائق ذهب')], default='consumable', max_length=20, verbose_name='نوع الأداة'),
        ),
    ]
