# Generated by Django 6.0 on 2025-12-26 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0015_installationtool_carat_installationtool_min_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoneCut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='كود الصنف')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الصنف')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'صنف حجارة',
                'verbose_name_plural': 'التصنيع - أصناف الحجارة',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='stone',
            name='stone_cut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stones', to='manufacturing.stonecut', verbose_name='شكل القطع'),
        ),
    ]
