# Generated by Django 6.0 on 2025-12-26 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0016_stonecut_stone_stone_cut'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود الموديل')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الموديل')),
                ('stone_cut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='manufacturing.stonecut', verbose_name='اسم الصنف')),
            ],
            options={
                'verbose_name': 'موديل حجارة',
                'verbose_name_plural': 'التصنيع - موديلات الحجارة',
                'ordering': ['stone_cut', 'code'],
            },
        ),
    ]
