# Generated by Django 6.0 on 2025-12-26 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0017_stonemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoneSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='كود الحجر')),
                ('stone_type', models.CharField(blank=True, max_length=50, verbose_name='نوع الحجر')),
                ('short_code', models.CharField(blank=True, max_length=20, verbose_name='الحرف المختصر')),
                ('weight_from', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='من وزن')),
                ('weight_to', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='الى وزن')),
                ('size_mm', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='مقاس mm')),
                ('price_per_carat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر القراط')),
                ('color', models.CharField(choices=[('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('G-H', 'G-H'), ('G H', 'G H'), ('G-I', 'G-I'), ('H-I', 'H-I')], default='G-H', max_length=10, verbose_name='اللون')),
                ('clarity', models.CharField(choices=[('IF', 'IF - Internally Flawless'), ('VVS', 'VVS - Very Very Slightly Included'), ('VVS1', 'VVS1'), ('VVS2', 'VVS2'), ('VS', 'VS - Very Slightly Included'), ('VS1', 'VS1'), ('VS2', 'VS2'), ('SI', 'SI - Slightly Included'), ('SI1', 'SI1'), ('SI2', 'SI2'), ('I1', 'I1 - Included')], default='VVS', max_length=10, verbose_name='درجة النقاء')),
                ('stone_cut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='manufacturing.stonecut', verbose_name='اسم الصنف')),
                ('stone_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='manufacturing.stonemodel', verbose_name='اسم الموديل')),
            ],
            options={
                'verbose_name': 'مقاس حجر',
                'verbose_name_plural': 'التصنيع - مقاسات الحجارة',
                'ordering': ['code'],
            },
        ),
    ]
