# Generated by Django 6.0 on 2025-12-26 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0018_stonesize'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoneCategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='الكود')),
                ('name', models.CharField(max_length=100, verbose_name='البيان')),
                ('short_code', models.CharField(max_length=10, verbose_name='البيان المختصر')),
                ('commission', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='العمولة')),
            ],
            options={
                'verbose_name': 'مجموعة أصناف ألماس',
                'verbose_name_plural': 'التصنيع - مجموعات أصناف الألماس',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='stonecut',
            name='category_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stone_cuts', to='manufacturing.stonecategorygroup', verbose_name='المجموعة'),
        ),
    ]
