# Generated by Django 6.0 on 2025-12-26 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0019_stonecategorygroup_stonecut_category_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingCylinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cylinder_number', models.CharField(max_length=50, unique=True, verbose_name='رقم السلندر')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='اسم/وصف السلندر')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cylinders/', verbose_name='صورة السلندر')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='المقاس')),
                ('capacity', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='السعة (جرام)')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='الخامة')),
                ('status', models.CharField(choices=[('available', 'متاح'), ('in_use', 'قيد الاستخدام'), ('maintenance', 'صيانة'), ('retired', 'خارج الخدمة')], default='available', max_length=20, verbose_name='الحالة')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الشراء')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='آخر صيانة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cylinders', to='manufacturing.workshop', verbose_name='الورشة')),
            ],
            options={
                'verbose_name': 'سلندر تصنيع',
                'verbose_name_plural': 'التصنيع - سلندرات السبك',
                'ordering': ['cylinder_number'],
            },
        ),
    ]
