# Generated by Django 6.0 on 2025-12-26 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0020_manufacturingcylinder'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionstage',
            name='cylinder',
            field=models.ForeignKey(blank=True, help_text='لمرحلة السبك فقط', null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.manufacturingcylinder', verbose_name='السلندر المستخدم'),
        ),
    ]
