# Generated by Django 6.0 on 2025-12-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0021_productionstage_cylinder'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='filings_balance_21',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='رصيد براده 21 (جرام)'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='filings_balance_24',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='رصيد براده 24 (جرام)'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='gold_balance_21',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='رصيد ذهب 21 (جرام)'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='gold_balance_24',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='رصيد ذهب 24 (جرام)'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='filings_balance_18',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='رصيد براده 18 (جرام)'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='gold_balance_18',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='رصيد ذهب 18 (جرام)'),
        ),
    ]
