# Generated by Django 6.0 on 2025-12-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0022_workshop_filings_balance_21_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='workshop_type',
            field=models.CharField(choices=[('internal', 'ورشة داخلية (مرتب ثابت)'), ('external', 'ورشة خارجية (بالجرام / قطعة)')], default='internal', max_length=20, verbose_name='نوع الورشة'),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='scrap_weight',
            field=models.DecimalField(decimal_places=3, default=0, help_text='المعيار المعتمد: 0.5% - 1.0%', max_digits=12, verbose_name='وزن الهالك/الخسية'),
        ),
    ]
