# Generated by Django 6.0 on 2025-12-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0023_workshop_workshop_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingorder',
            name='final_product_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/final/', verbose_name='صورة المنتج النهائي'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='qc_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات الجودة'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='qc_technician',
            field=models.CharField(blank=True, max_length=255, verbose_name='الفني الفاحص'),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('casting', 'سبك'), ('crafting', 'صياغة'), ('polishing', 'تلميع / واجهة'), ('qc_pending', 'قيد فحص الجودة'), ('completed', 'مكتمل / جاهز'), ('qc_failed', 'فحص جودة مرفوض'), ('cancelled', 'ملغى')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
    ]
