# Generated by Django 6.0 on 2025-12-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0024_manufacturingorder_final_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingorder',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('in_progress', 'تحت التشغيل'), ('casting', 'سبك'), ('crafting', 'صياغة'), ('polishing', 'تلميع / واجهة'), ('qc_pending', 'قيد فحص الجودة'), ('completed', 'مكتمل / جاهز'), ('qc_failed', 'فحص جودة مرفوض'), ('cancelled', 'ملغى')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
    ]
