# Generated by Django 6.0 on 2025-12-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0025_alter_manufacturingorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingorder',
            name='factory_margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='هامش ربح المصنع'),
        ),
    ]
