# Generated by Django 6.0 on 2025-12-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0026_manufacturingorder_factory_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingorder',
            name='powder_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='وزن البودر (المسترد)'),
        ),
    ]
