# Generated by Django 6.0 on 2025-12-26 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0027_manufacturingorder_powder_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, help_text='عند الاستخدام بالعدد', max_digits=10, verbose_name='الكمية المصروفة')),
                ('weight', models.DecimalField(decimal_places=3, default=0, help_text='عند الاستخدام بالجرام', max_digits=10, verbose_name='الوزن المصروف (جم)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_tools_list', to='manufacturing.manufacturingorder')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.installationtool', verbose_name='الأداة/المستلزم')),
            ],
            options={
                'verbose_name': 'مستلزم في أمر',
                'verbose_name_plural': 'مستلزمات الأوامر',
            },
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='tools',
            field=models.ManyToManyField(through='manufacturing.OrderTool', to='manufacturing.installationtool', verbose_name='المستلزمات والأدوات المستخدمة'),
        ),
    ]
