# Generated by Django 6.0 on 2025-12-27 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_activitylog_userprofile'),
        ('manufacturing', '0028_ordertool_manufacturingorder_tools'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionstage',
            options={},
        ),
        migrations.CreateModel(
            name='WorkshopTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(max_length=50, unique=True, verbose_name='رقم التحويل')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الوزن المحول')),
                ('status', models.CharField(choices=[('pending', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('date', models.DateField(auto_now_add=True, verbose_name='التاريخ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('carat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.carat', verbose_name='العيار')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_workshop_transfers', to=settings.AUTH_USER_MODEL, verbose_name='أكد الاستلام')),
                ('from_workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='manufacturing.workshop', verbose_name='من ورشة')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_workshop_transfers', to=settings.AUTH_USER_MODEL, verbose_name='بادر بالتحويل')),
                ('to_workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='manufacturing.workshop', verbose_name='إلى ورشة')),
            ],
            options={
                'verbose_name': 'تحويل بين الورش',
                'verbose_name_plural': 'التصنيع - تحويلات الورش',
            },
        ),
    ]
