# Generated by Django 6.0 on 2025-12-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0029_alter_productionstage_options_workshoptransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionstage',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت التسليم/الانتهاء'),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت البدء الفعلي'),
        ),
    ]
