# Generated by Django 6.0 on 2025-12-30 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0030_productionstage_end_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionstage',
            name='is_transferred',
            field=models.BooleanField(default=False, verbose_name='تم التحويل تلقائياً'),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='loss_weight',
            field=models.DecimalField(decimal_places=3, default=0, help_text='الفرق المتبقي', max_digits=10, verbose_name='وزن الخسية (هالك)'),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='next_workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_stages', to='manufacturing.workshop', verbose_name='تحويل إلى الورشة التالية'),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='powder_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='وزن البودر (براده)'),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.workshop', verbose_name='الورشة/الصنايعي المنفذ'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='scrap_balance_18',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='رصيد خسية 18 (جرام)'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='scrap_balance_21',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='رصيد خسية 21 (جرام)'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='scrap_balance_24',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='رصيد خسية 24 (جرام)'),
        ),
        migrations.AlterField(
            model_name='productionstage',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت تسليم (خروج)'),
        ),
        migrations.AlterField(
            model_name='productionstage',
            name='input_weight',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الوزن الدخول'),
        ),
        migrations.AlterField(
            model_name='productionstage',
            name='output_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='الوزن الخروج'),
        ),
        migrations.AlterField(
            model_name='productionstage',
            name='stage_name',
            field=models.CharField(choices=[('tazgah_qasem', 'تزجة قاسم (تجميع)'), ('laser', 'ليزر (لحام/زيادة)'), ('mounting_pablo', 'تركيب بابلو'), ('polishing', 'الجلي والتلميع'), ('mounting_manmouk', 'تركيب منموى (نهائي)'), ('design', 'تصميم / 3D Design'), ('printing', 'طباعة الشمع / 3D Printing'), ('wax_injection', 'حقن الشمع / Wax Injection'), ('wax_setting', 'تركيب الشمع / Wax Setting'), ('casting', 'السبك / Casting'), ('filing', 'البرد والتجهيز / Filing'), ('mounting', 'التركيب / Mounting'), ('setting', 'تركيب الأحجار / Stone Setting'), ('plating', 'الطلاء / Plating'), ('enamel', 'المينا / Enamel'), ('chains', 'السلاسل / Chains'), ('stamping', 'الدمغة / Stamping'), ('repair', 'الصيانة / Repairs'), ('qc', 'مراقبة الجودة / Quality Control')], default='tazgah_qasem', max_length=20, verbose_name='اسم المرحلة'),
        ),
        migrations.AlterField(
            model_name='productionstage',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت بدء (استلام)'),
        ),
        migrations.AlterField(
            model_name='productionstage',
            name='technician',
            field=models.CharField(blank=True, max_length=255, verbose_name='اسم الفني (نص)'),
        ),
    ]
