# Generated by Django 6.0 on 2025-12-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0031_productionstage_is_transferred_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stone',
            name='unit',
            field=models.CharField(choices=[('carat', 'قيراط (Carat)'), ('cm', 'سنتيمتر (CM)')], default='carat', max_length=20, verbose_name='الوحدة'),
        ),
    ]
