# Generated by Django 6.0 on 2025-12-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0032_alter_stone_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstone',
            name='quantity_issued',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='الكمية المصروفة الفعلية'),
        ),
        migrations.AddField(
            model_name='orderstone',
            name='quantity_required',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='الكمية المطلوبة (في المنتج)'),
        ),
        migrations.AlterField(
            model_name='orderstone',
            name='quantity',
            field=models.DecimalField(decimal_places=3, editable=False, max_digits=10, verbose_name='إجمالي المصروف'),
        ),
    ]
