# Generated by Django 6.0 on 2025-12-30 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0033_orderstone_quantity_issued_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstone',
            name='production_stage',
            field=models.ForeignKey(blank=True, help_text='المرحلة التي تم فيها صرف الأحجار', null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.productionstage', verbose_name='مرحلة الصرف (التركيب)'),
        ),
    ]
