# Generated by Django 4.2.27 on 2026-01-01 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0034_orderstone_production_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_name', models.CharField(help_text='مثال: تكاليف شهر يناير 2026', max_length=100, verbose_name='اسم العهدة/الفترة')),
                ('start_date', models.DateField(verbose_name='من تاريخ')),
                ('end_date', models.DateField(verbose_name='إلى تاريخ')),
                ('total_electricity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي الكهرباء')),
                ('total_water', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي المياه')),
                ('total_gas', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي الغاز')),
                ('total_rent', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي الإيجار')),
                ('total_salaries', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي رواتب إدارية')),
                ('total_other', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مصروفات أخرى')),
                ('allocation_basis', models.CharField(choices=[('weight', 'حسب وزن الذهب المنتج (Output Weight)'), ('labor', 'حسب أجر التصنيع (Labor Cost)')], default='weight', max_length=20, verbose_name='أساس التوزيع')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('applied', 'تم الترحيل (مغلق)')], default='draft', max_length=20, verbose_name='الحالة')),
                ('total_production_weight_snapshot', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=15, verbose_name='إجمالي الوزن المنتج في الفترة')),
                ('total_labor_cost_snapshot', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='إجمالي أجور التصنيع في الفترة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'توزيع تكاليف المصنع',
                'verbose_name_plural': 'التصنيع - تكاليف المصنع',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='overhead_electricity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='نصيب الكهرباء'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='overhead_gas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='نصيب الغاز'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='overhead_other',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='نصيب مصاريف أخرى'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='overhead_rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='نصيب الإيجار'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='overhead_salaries',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='نصيب الرواتب'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='overhead_water',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='نصيب المياه'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='cost_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.costallocation', verbose_name='فترة التكاليف'),
        ),
    ]
