# Generated by Django 4.2.27 on 2026-01-01 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_alter_expensevoucher_expense_category_and_more'),
        ('manufacturing', '0035_costallocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costallocation',
            name='cost_center',
            field=models.ForeignKey(blank=True, help_text='إذا تم الاختيار، سيتم جلب المصاريف الخاصة بهذا المركز فقط (مثل: المصنع)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.costcenter', verbose_name='مركز التكلفة'),
        ),
    ]
