# Generated by Django 4.2.27 on 2026-01-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0036_costallocation_cost_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='costallocation',
            name='net_labor_profit_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='صافي ربح قطاع التصنيع (بعد الأجور والمصاريف)'),
        ),
        migrations.AddField(
            model_name='costallocation',
            name='total_labor_income_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='إجمالي الدخل من أجور التصنيع (شامل الهامش)'),
        ),
        migrations.AlterField(
            model_name='costallocation',
            name='total_labor_cost_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='إجمالي أجور الورش (الخارجية)'),
        ),
    ]
