# Generated by Django 4.2.27 on 2026-01-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0037_costallocation_net_labor_profit_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingorder',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('in_progress', 'تحت التشغيل'), ('casting', 'سبك'), ('crafting', 'صياغة'), ('polishing', 'تلميع / واجهة'), ('tribolish', 'الترابولش'), ('qc_pending', 'قيد فحص الجودة'), ('completed', 'مكتمل / جاهز'), ('qc_failed', 'فحص جودة مرفوض'), ('cancelled', 'ملغى')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='productionstage',
            name='stage_name',
            field=models.CharField(choices=[('tazgah_qasem', 'تزجة قاسم (تجميع)'), ('laser', 'ليزر (لحام/زيادة)'), ('mounting_pablo', 'تركيب بابلو'), ('polishing', 'الجلي والتلميع'), ('mounting_manmouk', 'تركيب منموى (نهائي)'), ('design', 'تصميم / 3D Design'), ('printing', 'طباعة الشمع / 3D Printing'), ('wax_injection', 'حقن الشمع / Wax Injection'), ('wax_setting', 'تركيب الشمع / Wax Setting'), ('casting', 'السبك / Casting'), ('filing', 'البرد والتجهيز / Filing'), ('mounting', 'التركيب / Mounting'), ('setting', 'تركيب الأحجار / Stone Setting'), ('plating', 'الطلاء / Plating'), ('enamel', 'المينا / Enamel'), ('chains', 'السلاسل / Chains'), ('stamping', 'الدمغة / Stamping'), ('repair', 'الصيانة / Repairs'), ('qc', 'مراقبة الجودة / Quality Control'), ('tribolish', 'الترابولش (Tribolish)')], default='tazgah_qasem', max_length=20, verbose_name='اسم المرحلة'),
        ),
    ]
