# Generated by Django 4.2.27 on 2026-01-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0038_alter_manufacturingorder_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingorder',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('in_progress', 'تحت التشغيل'), ('casting', 'سبك'), ('crafting', 'صياغة'), ('polishing', 'تلميع / واجهة'), ('tribolish', 'الترابولش'), ('merged', 'مدمج مع أمر آخر'), ('qc_pending', 'قيد فحص الجودة'), ('completed', 'مكتمل / جاهز'), ('qc_failed', 'فحص جودة مرفوض'), ('cancelled', 'ملغى')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
    ]
