# Generated by Django 4.2.27 on 2026-01-04 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manufacturing', '0039_alter_manufacturingorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stone',
            name='stone_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stones_inventory', to='manufacturing.stonesize', verbose_name='المقاس المحدد'),
        ),
        migrations.AlterField(
            model_name='stone',
            name='unit',
            field=models.CharField(choices=[('carat', 'قيراط (Carat)'), ('gram', 'جرام (Gram)'), ('cm', 'سنتيمتر (CM)')], default='carat', max_length=20, verbose_name='الوحدة'),
        ),
        migrations.CreateModel(
            name='StoneInventoryAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الجرد')),
                ('system_stock', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='الرصيد الدفتري')),
                ('physical_stock', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='الرصيد الفعلي')),
                ('difference', models.DecimalField(decimal_places=3, editable=False, max_digits=10, verbose_name='الفرق')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات الجرد')),
                ('audited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('stone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='manufacturing.stone', verbose_name='الحجر')),
            ],
            options={
                'verbose_name': 'جرد أحجار',
                'verbose_name_plural': 'التصنيع - جرد الأحجار',
                'ordering': ['-audit_date'],
            },
        ),
    ]
