# Generated by Django 4.2.27 on 2026-01-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0040_stone_stone_size_alter_stone_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stone',
            name='current_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='العدد الحالي (قطعة)'),
        ),
        migrations.AddField(
            model_name='stoneinventoryaudit',
            name='difference_quantity',
            field=models.IntegerField(default=0, editable=False, verbose_name='الفرق (عدد)'),
        ),
        migrations.AddField(
            model_name='stoneinventoryaudit',
            name='physical_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='العدد الفعلي'),
        ),
        migrations.AddField(
            model_name='stoneinventoryaudit',
            name='system_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='العدد الدفتري'),
        ),
        migrations.AlterField(
            model_name='stone',
            name='current_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='الرصيد الحالي (وزن)'),
        ),
        migrations.AlterField(
            model_name='stoneinventoryaudit',
            name='difference',
            field=models.DecimalField(decimal_places=3, editable=False, max_digits=10, verbose_name='الفرق (وزن)'),
        ),
        migrations.AlterField(
            model_name='stoneinventoryaudit',
            name='physical_stock',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='الرصيد الفعلي (وزن)'),
        ),
        migrations.AlterField(
            model_name='stoneinventoryaudit',
            name='system_stock',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='الرصيد الدفتري (وزن)'),
        ),
    ]
