# Generated by Django 4.2.27 on 2026-01-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0041_stone_current_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingorder',
            name='start_date',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='تاريخ البدء'),
        ),
        migrations.AlterField(
            model_name='workshopsettlement',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='تاريخ التسوية'),
        ),
    ]
