# Generated by Django 4.2.27 on 2026-01-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0042_alter_manufacturingorder_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='default_stage_name',
            field=models.CharField(choices=[('tazgah_qasem', 'تزجة قاسم (تجميع)'), ('laser', 'ليزر (لحام/زيادة)'), ('mounting_pablo', 'تركيب بابلو'), ('polishing', 'الجلي والتلميع'), ('mounting_manmouk', 'تركيب منموى (نهائي)'), ('design', 'تصميم / 3D Design'), ('printing', 'طباعة الشمع / 3D Printing'), ('wax_injection', 'حقن الشمع / Wax Injection'), ('wax_setting', 'تركيب الشمع / Wax Setting'), ('casting', 'السبك / Casting'), ('filing', 'البرد والتجهيز / Filing'), ('mounting', 'التركيب / Mounting'), ('setting', 'تركيب الأحجار / Stone Setting'), ('plating', 'الطلاء / Plating'), ('enamel', 'المينا / Enamel'), ('chains', 'السلاسل / Chains'), ('stamping', 'الدمغة / Stamping'), ('repair', 'الصيانة / Repairs'), ('qc', 'مراقبة الجودة / Quality Control'), ('tribolish', 'الترابولش (Tribolish)')], default='tazgah_qasem', help_text='المرحلة التي تظهر تلقائياً عند تحويل الشغل لهذه الورشة', max_length=20, verbose_name='المرحلة الافتراضية'),
        ),
    ]
