# Generated by Django 4.2.27 on 2026-01-06 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0043_workshop_default_stage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshoptransfer',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='manufacturing.manufacturingorder', verbose_name='أمر التصنيع'),
        ),
    ]
