# Generated by Django 4.2.27 on 2026-01-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0044_workshoptransfer_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='display_order',
            field=models.IntegerField(default=0, help_text='الرقم الأقل يظهر أولاً', verbose_name='ترتيب العرض'),
        ),
    ]
