# Generated by Django 4.2.27 on 2026-01-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0045_workshop_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='is_active',
            field=models.BooleanField(default=True, help_text='إلغاء التفعيل يخفي الورشة من الوردية السحرية', verbose_name='نشطة (تظهر في اللوحة)'),
        ),
    ]
