# Generated by Django 4.2.27 on 2026-01-07 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_item_barcode'),
        ('manufacturing', '0046_workshop_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingorder',
            name='item_category',
            field=models.ForeignKey(blank=True, help_text='سيتم توليد الباركود تلقائياً بناءً على هذا التصنيف', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category', verbose_name='تصنيف الصنف الناتج'),
        ),
    ]
