# Generated by Django 6.0 on 2025-12-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('vat_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='VAT Number')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('wedding_anniversary', models.DateField(blank=True, null=True)),
                ('total_purchases_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('loyalty_points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
