# Generated by Django 6.0 on 2025-12-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_customer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gold_balance_18',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='رصيد ذهب 18 (جم)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='gold_balance_21',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='رصيد ذهب 21 (جم)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='gold_balance_24',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='رصيد ذهب 24 (جم)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='money_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='الرصيد المدين/الدائن للعميل', max_digits=15, verbose_name='الرصيد النقدي'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='loyalty_points',
            field=models.IntegerField(default=0, verbose_name='نقاط الولاء'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_purchases_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي المشتريات'),
        ),
    ]
