# Generated by Django 6.0 on 2025-12-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_customer_gold_balance_18_customer_gold_balance_21_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المورد')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='رقم الجوال')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='الشخص المسؤول')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('vat_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم الضريبي')),
                ('supplier_type', models.CharField(choices=[('gold_office', 'مكتب ذهب'), ('factory', 'مصنع'), ('trader', 'تاجر كسر'), ('other', 'آخر')], default='factory', max_length=20, verbose_name='نوع المورد')),
                ('money_balance', models.DecimalField(decimal_places=2, default=0, help_text='الرصيد المدين/الدائن للمورد', max_digits=15, verbose_name='الرصيد النقدي')),
                ('gold_balance_18', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='رصيد ذهب 18 (جم)')),
                ('gold_balance_21', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='رصيد ذهب 21 (جم)')),
                ('gold_balance_24', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='رصيد ذهب 24 (جم)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'الموردين',
            },
        ),
    ]
