# Generated by Django 6.0 on 2025-12-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='primary_carat',
            field=models.IntegerField(default=18, help_text='العيار الذي يتم التعامل به غالباً', verbose_name='العيار الأساسي'),
        ),
    ]
