# Generated by Django 4.2.27 on 2026-01-03 13:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_invoice_total_stones_value_and_more'),
        ('core', '0006_activitylog_userprofile'),
        ('crm', '0007_alter_supplier_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('sale', 'مبيعات'), ('payment', 'دفع نقدي'), ('gold_in', 'إيداع ذهب'), ('gold_out', 'صرف ذهب'), ('barter', 'مقايضة'), ('khasia', 'خسية/خصم'), ('adjustment', 'تسوية رصيد')], max_length=20, verbose_name='نوع الحركة')),
                ('cash_debit', models.DecimalField(decimal_places=2, default=0, help_text='المبالغ المستحقة على العميل', max_digits=15, verbose_name='مدين (عليه)')),
                ('cash_credit', models.DecimalField(decimal_places=2, default=0, help_text='المبالغ المدفوعة من العميل', max_digits=15, verbose_name='دائن (له)')),
                ('gold_debit', models.DecimalField(decimal_places=3, default=0, help_text='وزن الذهب الذي استلمه العميل', max_digits=15, verbose_name='وزن مدين (سحب)')),
                ('gold_credit', models.DecimalField(decimal_places=3, default=0, help_text='وزن الذهب الذي قدمه العميل (كسر/مقايضة)', max_digits=15, verbose_name='وزن دائن (إيداع)')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الحركة')),
                ('description', models.TextField(blank=True, verbose_name='البيان / الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.carat', verbose_name='العيار')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_transactions', to='crm.customer', verbose_name='العميل')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.invoice', verbose_name='الفاتورة المرتبطة')),
            ],
            options={
                'verbose_name': 'حركة حساب عميل',
                'verbose_name_plural': 'حركات حسابات العملاء',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
