# Generated by Django 4.2.27 on 2026-01-03 16:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_carat_base_weight'),
        ('crm', '0008_customertransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'مشتريات/توريد'), ('payment', 'دفعة نقدية (له)'), ('return_cash', 'رد نقدية (منه)'), ('gold_in', 'توريد ذهب (له)'), ('gold_out', 'صرف ذهب (عليه)'), ('adjustment', 'تسوية رصيد')], max_length=20, verbose_name='نوع الحركة')),
                ('cash_debit', models.DecimalField(decimal_places=2, default=0, help_text='المبالغ التي استلمها المورد (دفعة)', max_digits=15, verbose_name='مدين (عليه)')),
                ('cash_credit', models.DecimalField(decimal_places=2, default=0, help_text='قيمة البضاعة الموردة', max_digits=15, verbose_name='دائن (له)')),
                ('gold_debit', models.DecimalField(decimal_places=3, default=0, help_text='وزن أخذه المورد', max_digits=15, verbose_name='وزن مدين (سحب)')),
                ('gold_credit', models.DecimalField(decimal_places=3, default=0, help_text='وزن ورده المورد', max_digits=15, verbose_name='وزن دائن (إيداع)')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الحركة')),
                ('description', models.TextField(blank=True, verbose_name='البيان / الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.carat', verbose_name='العيار')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_transactions', to='crm.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'حركة حساب مورد',
                'verbose_name_plural': 'حركات حسابات الموردين',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
