# Generated by Django 6.0 on 2025-12-24 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'فاتورة مبيعات', 'verbose_name_plural': 'المبيعات - الفواتير'},
        ),
        migrations.AlterModelOptions(
            name='oldgoldreturn',
            options={'verbose_name': 'ذهب مستبدل', 'verbose_name_plural': 'المبادلات - الذهب المستعمل'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='exchange_gold_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Exchange Gold Weight'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='exchange_value_deducted',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Exchange Value Deducted'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Grand Total'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_exchange',
            field=models.BooleanField(default=False, verbose_name='Is Exchange?'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('card', 'بطاقة / مدى'), ('bank_transfer', 'تحويل بنكي'), ('mixed', 'دفع مختلط')], default='cash', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_gold_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Gold Value'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_labor_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Labor Value'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Tax (VAT)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='zatca_qr_code',
            field=models.TextField(blank=True, verbose_name='ZATCA QR Code'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='zatca_uuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='ZATCA UUID'),
        ),
    ]
