# Generated by Django 6.0 on 2025-12-24 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_branch_options_alter_carat_options_and_more'),
        ('sales', '0002_alter_invoice_options_alter_oldgoldreturn_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المندوب')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('commission_type', models.CharField(choices=[('percentage', 'نسبة مئوية'), ('fixed', 'مبلغ ثابت')], default='percentage', max_length=20, verbose_name='نوع العمولة')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, help_text='إذا كانت نسبة مئوية، أدخل القيمة (مثال: 2.5 تعني 2.5%)', max_digits=10, verbose_name='نسبة/قيمة العمولة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي المبيعات')),
                ('total_commission', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي العمولات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch', verbose_name='الفرع المسؤول عنه')),
            ],
            options={
                'verbose_name': 'مندوب مبيعات',
                'verbose_name_plural': 'المبيعات - المندوبين',
            },
        ),
        migrations.CreateModel(
            name='SalesRepTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('commission', 'عمولة'), ('bonus', 'مكافأة'), ('deduction', 'خصم'), ('payment', 'صرف')], max_length=20, verbose_name='نوع الحركة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.invoice', verbose_name='الفاتورة')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='sales.salesrepresentative', verbose_name='المندوب')),
            ],
            options={
                'verbose_name': 'حركة مندوب',
                'verbose_name_plural': 'المبيعات - حركات المندوبين',
            },
        ),
    ]
