# Generated by Django 6.0 on 2025-12-24 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesrepresentative_salesreptransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sales_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sales.salesrepresentative', verbose_name='المندوب'),
        ),
    ]
