# Generated by Django 6.0 on 2025-12-24 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_invoice_sales_rep'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrepresentative',
            name='user',
            field=models.OneToOneField(blank=True, help_text='لتمكين الدخول من التطبيق', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم المرتبط'),
        ),
    ]
