# Generated by Django 4.2.27 on 2026-01-01 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_activitylog_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0007_alter_supplier_phone'),
        ('sales', '0006_invoice_confirmed_at_invoice_confirmed_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'فاتورة مبيعات', 'verbose_name_plural': 'سجل فواتير المبيعات'},
        ),
        migrations.AddField(
            model_name='salesrepresentative',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.branch', verbose_name='الفرع'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='crm.customer', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإجمالي النهائي'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم الفاتورة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('card', 'بطاقة / مدى'), ('bank_transfer', 'تحويل بنكي'), ('mixed', 'دفع مختلط')], default='cash', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_gold_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قيمة الذهب'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_labor_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قيمة المصنعية'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ضريبة القيمة المضافة'),
        ),
    ]
