# Generated by Django 4.2.27 on 2026-01-01 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_item_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0007_alter_supplier_phone'),
        ('sales', '0007_alter_invoice_options_salesrepresentative_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحجز')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='crm.customer', verbose_name='العميل')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='inventory.item', verbose_name='القطعة')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='المندوب')),
            ],
            options={
                'verbose_name': 'حجز',
                'verbose_name_plural': 'الحجوزات',
                'ordering': ['-created_at'],
            },
        ),
    ]
