# Generated by Django 4.2.27 on 2026-01-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='sold_factory_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='إجمالي التكلفة الصناعية المخزنة في القطعة وقت البيع', max_digits=10, verbose_name='تكلفة المصنع (أجور + مصاريف)'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='sold_gold_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الذهب وقت البيع'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='sold_labor_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='أجر المصنعية (المحصل)'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='sold_weight',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='الوزن المباع'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='إجمالي السطر'),
        ),
    ]
