# Generated by Django 4.2.27 on 2026-01-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_invoiceitem_sold_factory_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_stones_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قيمة الأحجار'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='sold_stone_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قيمة الفصوص/الأحجار'),
        ),
    ]
