# Generated by Django 4.2.27 on 2026-01-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_invoice_total_stones_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء'),
        ),
    ]
