# Generated by Django 4.2.27 on 2026-01-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_invoice_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_gold_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='إجمالي وزن الذهب'),
        ),
    ]
